#!/bin/bash
<<DOCO
Date:       9 August 2013
Author:     rdc@mote.org
Purpose:    Rsync data files (sbd/logs) from coolcomms
            to /var/www/html/deployments/vehicle
            Process log and sbd files to build SQLite DB file,
            CSV output for GCOOS, KMZ file and plots.
            This is for use DURING a mission. Post-mission
            processing is performed using different scripts.
DOCO

 if [ "$#" != 2 ];then
    echo "Usage: glider_date_pipeline vehicle_name DEBUG_LEVEL"
else
    echo "Glider Data Pipeline for $1 initiated at $(date)..."
    DATA_DIR="/var/www/html/deployments/$1"
    echo $DATA_DIR
    echo "Rsyncing sbd files from coolcomms for $1..."
    rsync -av coolcomms:/var/opt/gmc/gliders/waldo/from-glider/*.sbd "$DATA_DIR/binary_files/sbd/"
    echo "Rsyncing tbd files from coolcomms for $1..."
    rsync -av coolcomms:/var/opt/gmc/gliders/waldo/from-glider/*.tbd "$DATA_DIR/binary_files/tbd/"
    echo "Rsyncing log files from coolcomms for $1..."
    rsync -av coolcomms:/var/opt/gmc/gliders/waldo/logs/*.log "$DATA_DIR/ascii_files/logs/"
    echo "Processing $1 data and log files..."
    ./process_mission_files.py $1 $2
    echo "Generating KMZ for $1..."
    echo "Generating plots for $1..."
    echo "$1 completed at $(date)..."
fi
